"use client"

import Image from "next/image"
import Link from "next/link"
import { ArrowRight, BarChart3, Bell, Check, ChevronRight, CircleGauge, Lightbulb, Menu, ShieldCheck, Sparkles, X, Zap } from "lucide-react"
import { useEffect, useState } from "react"

const steps = [
  { icon: CircleGauge, title: "Detectar", text: "Encontramos picos, horários e equipamentos que fogem do padrão." },
  { icon: Sparkles, title: "Explicar", text: "Traduzimos a conta em uma história simples, sem jargão técnico." },
  { icon: Lightbulb, title: "Recomendar", text: "Você recebe ações práticas, priorizadas pelo impacto." },
]

export function EnergialertaLanding() {
  const [open, setOpen] = useState(false)
  const [headerVisible, setHeaderVisible] = useState(true)

  useEffect(() => {
    let lastScrollY = window.scrollY
    const handleScroll = () => {
      const currentScrollY = window.scrollY
      setHeaderVisible(currentScrollY < 24 || currentScrollY < lastScrollY)
      lastScrollY = currentScrollY
    }
    window.addEventListener("scroll", handleScroll, { passive: true })
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <header className={`sticky top-0 z-40 mx-auto flex max-w-7xl items-center justify-between bg-background/90 px-6 py-5 backdrop-blur-md transition-transform duration-300 md:relative md:bg-transparent md:backdrop-blur-0 ${headerVisible ? "translate-y-0" : "-translate-y-full md:translate-y-0"}`}>
        <Link href="/" aria-label="EnergiAlerta - início"><Image src="/energialerta-logo.png" alt="EnergiAlerta" width={190} height={58} className="logo-dark h-9 w-[150px] object-cover object-center" priority /></Link>
        <nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#como-funciona" className="transition-all duration-300 hover:-translate-y-0.5 hover:text-foreground active:scale-95">Como funciona</a><a href="#para-quem" className="transition-all duration-300 hover:-translate-y-0.5 hover:text-foreground active:scale-95">Para quem é</a><a href="#impacto" className="transition-all duration-300 hover:-translate-y-0.5 hover:text-foreground active:scale-95">Impacto</a></nav>
        <div className="hidden items-center gap-4 md:flex"><Link href="/login" className="text-sm text-muted-foreground transition-all hover:-translate-y-0.5 hover:text-foreground active:scale-95">Entrar</Link><Link href="/login" className="rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition-all hover:scale-[1.03] active:scale-95">Ver meu consumo <ArrowRight className="ml-1 inline size-4 transition-transform group-hover:translate-x-1" /></Link></div>
        <button className="rounded-lg border border-border p-2 transition-all duration-300 hover:border-primary/50 hover:bg-primary/10 active:scale-90 active:rotate-6 md:hidden" onClick={() => setOpen(!open)} aria-label={open ? "Fechar menu" : "Abrir menu"}>{open ? <X className="size-5" /> : <Menu className="size-5" />}</button>
      </header>
      {open && <div className="absolute inset-x-4 top-20 z-30 rounded-2xl border border-border bg-card p-5 shadow-2xl md:hidden"><nav className="flex flex-col gap-5 text-sm"><a href="#como-funciona" onClick={() => setOpen(false)}>Como funciona</a><a href="#para-quem" onClick={() => setOpen(false)}>Para quem é</a><Link href="/login" className="rounded-full bg-primary px-4 py-3 text-center font-semibold text-primary-foreground">Acessar painel</Link></nav></div>}

      <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 pb-24 pt-16 lg:grid-cols-[1fr_0.9fr] lg:px-10 lg:pb-32 lg:pt-24">
        <div className="relative z-10 animate-reveal-up"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-1.5 rounded-full bg-primary shadow-[0_0_12px_currentColor]" /> Inteligência para cada kWh</div><h1 className="max-w-3xl font-display text-5xl font-semibold leading-[1.02] tracking-[-0.05em] text-balance sm:text-6xl lg:text-7xl">Sua conta mostra o gasto.<br /><span className="text-primary">Nós mostramos o desperdício.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">O EnergiAlerta transforma dados de energia em decisões claras. Detecte anomalias, entenda o que está acontecendo e reduza custos sem adivinhação.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="rounded-full bg-primary px-6 py-3.5 text-center text-sm font-bold text-primary-foreground transition hover:scale-[1.02]">Começar agora <ArrowRight className="ml-2 inline size-4" /></Link><a href="#como-funciona" className="rounded-full border border-border px-6 py-3.5 text-center text-sm font-semibold transition hover:bg-secondary">Conhecer a plataforma <ChevronRight className="ml-1 inline size-4" /></a></div><div className="mt-10 flex items-center gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" /> Dados protegidos</span><span className="flex items-center gap-2"><Zap className="size-4 text-primary" /> Ações que geram impacto</span></div></div>
        <div className="relative animate-reveal-up [animation-delay:180ms]"><div className="absolute -inset-16 rounded-full bg-primary/10 blur-3xl" /><div className="relative overflow-hidden rounded-3xl border border-border bg-card p-5 shadow-2xl shadow-primary/5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-muted-foreground">Consumo deste mês</p><p className="mt-2 font-mono text-4xl font-semibold tracking-tight">12.840 <span className="text-base font-normal text-muted-foreground">kWh</span></p><p className="mt-2 text-xs text-primary">↓ 8,4% vs. mês anterior</p></div><div className="rounded-xl bg-primary/10 p-3 text-primary"><BarChart3 className="size-5" /></div></div><div className="mt-8 flex h-40 items-end gap-2 border-b border-border/70 px-1">{[34,48,42,65,55,78,67,92,71,83,62,48,56,43,50].map((h, i) => <div key={i} className={`animate-bar-grow flex-1 rounded-t-sm ${i === 7 ? "bg-primary" : "bg-primary/25"}`} style={{ height: `${h}%` }} />)}</div><div className="mt-5 flex items-center justify-between rounded-xl border border-primary/20 bg-primary/5 p-4"><div className="flex gap-3"><div className="rounded-lg bg-primary/15 p-2 text-primary"><Bell className="size-4" /></div><div><p className="text-sm font-semibold">Anomalia detectada</p><p className="mt-1 text-xs text-muted-foreground">Ar-condicionado consumiu 31% a mais</p></div></div><ChevronRight className="size-4 text-muted-foreground" /></div></div></div>
      </section>

      <section id="como-funciona" className="border-y border-border/70 bg-card/30 px-6 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Do dado à decisão</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Energia complexa.<br />Clareza na prática.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{steps.map(({ icon: Icon, title, text }) => <div key={title} className="animate-reveal-up rounded-2xl border border-border bg-background p-6 transition duration-300 hover:-translate-y-1 hover:border-primary/40"><div className="flex items-center justify-between"><div className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="size-5" /></div><span className="font-mono text-xs text-muted-foreground">0{steps.findIndex(s => s.title === title) + 1}</span></div><h3 className="mt-8 font-display text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>

      <section id="para-quem" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[0.8fr_1fr] lg:px-10"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Feito para agir</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Menos desperdício.<br />Mais controle.</h2><p className="mt-6 max-w-md leading-7 text-muted-foreground">Uma visão compartilhada para quem cuida da operação, da sustentabilidade ou da própria casa.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-primary p-6 text-primary-foreground"><Zap className="size-6" /><h3 className="mt-10 text-xl font-semibold">Operações</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/75">Antecipe falhas e priorize onde cada ação economiza mais.</p></div><div className="rounded-2xl border border-border p-6"><BarChart3 className="size-6 text-primary" /><h3 className="mt-10 text-xl font-semibold">Gestão</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Conecte consumo, custo e metas em uma única leitura.</p></div><div className="rounded-2xl border border-border p-6 sm:col-span-2"><Check className="size-6 text-primary" /><h3 className="mt-8 text-xl font-semibold">Sustentabilidade com evidência</h3><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Meça o que foi evitado e transforme eficiência energética em resultado visível.</p></div></div></section>
      <section id="impacto" className="px-6 pb-20 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-3xl bg-secondary p-8 sm:p-12 lg:flex-row lg:items-center"><div><p className="text-sm text-primary">Pronto para enxergar diferente?</p><h2 className="mt-3 max-w-2xl font-display text-3xl font-semibold tracking-tight sm:text-4xl">O próximo kWh economizado começa com uma boa pergunta.</h2></div><Link href="/login" className="shrink-0 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-primary-foreground">Acessar meu painel <ArrowRight className="ml-2 inline size-4" /></Link></div></section>
      <footer className="mx-auto flex max-w-7xl flex-col gap-3 border-t border-border px-6 py-7 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>© 2026 EnergiAlerta</span><div className="flex gap-4"><Link href="/cookies" className="transition hover:text-primary">Cookies</Link><Link href="/privacidade" className="transition hover:text-primary">Privacidade</Link></div></footer>
    </main>
  )
}
